image: golang:1.22
stages:
  - building
  - testing
  - deploying

build-app:
  stage: building
  script: go build .

run-tests:
  stage: testing
  services:
    - postgres:16.2
  variables:
    POSTGRES_PASSWORD: postgres
    DB_HOST: postgres
    DB_PORT: 5432
  script: go test -v ./...

deploy:
  stage: deploying
  script: echo 'Hi from deploy'